name: Deploy my feature branch to nonprod bucket

# trigger on all push events to main branch
on:
  push:
    branches:
      - feature*
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: my-bucket-sp1512
    steps:
      - name: checkout feature branch
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node jobs
        uses: actions/setup-node@v2
        with: 
          node-vesion: 14
      - name: build site
        run: |
          npm ci
          npm run build
          npm audit fix --force
      - name: deploy the site to s3 bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read

